//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpreadSheetsReports.WpfUi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpreadSheetsReports.WpfUi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Alignment_Horizontal {
            get {
                return ResourceManager.GetString("Alignment_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent:.
        /// </summary>
        public static string Alignment_Indent {
            get {
                return ResourceManager.GetString("Alignment_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string Alignment_Rotation {
            get {
                return ResourceManager.GetString("Alignment_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink to Fit.
        /// </summary>
        public static string Alignment_ShrinkToFit {
            get {
                return ResourceManager.GetString("Alignment_ShrinkToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text alignment.
        /// </summary>
        public static string Alignment_TextAlignment {
            get {
                return ResourceManager.GetString("Alignment_TextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text control.
        /// </summary>
        public static string Alignment_TextControl {
            get {
                return ResourceManager.GetString("Alignment_TextControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Alignment_Vertical {
            get {
                return ResourceManager.GetString("Alignment_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapt Text.
        /// </summary>
        public static string Alignment_WrapText {
            get {
                return ResourceManager.GetString("Alignment_WrapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string Border_Border {
            get {
                return ResourceManager.GetString("Border_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Border_Line {
            get {
                return ResourceManager.GetString("Border_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string Border_LineColor {
            get {
                return ResourceManager.GetString("Border_LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style:.
        /// </summary>
        public static string Border_LineStyle {
            get {
                return ResourceManager.GetString("Border_LineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Border_None {
            get {
                return ResourceManager.GetString("Border_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Border_Text {
            get {
                return ResourceManager.GetString("Border_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string CellStyleEditor_Aligment {
            get {
                return ResourceManager.GetString("CellStyleEditor_Aligment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string CellStyleEditor_Border {
            get {
                return ResourceManager.GetString("CellStyleEditor_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string CellStyleEditor_Font {
            get {
                return ResourceManager.GetString("CellStyleEditor_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Font_Bold {
            get {
                return ResourceManager.GetString("Font_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string Font_Color {
            get {
                return ResourceManager.GetString("Font_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string Font_Font {
            get {
                return ResourceManager.GetString("Font_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size:.
        /// </summary>
        public static string Font_FontSize {
            get {
                return ResourceManager.GetString("Font_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Style:.
        /// </summary>
        public static string Font_FontStyle {
            get {
                return ResourceManager.GetString("Font_FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Font_Italic {
            get {
                return ResourceManager.GetString("Font_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainWindow_New {
            get {
                return ResourceManager.GetString("MainWindow_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainWindow_Open {
            get {
                return ResourceManager.GetString("MainWindow_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_Save {
            get {
                return ResourceManager.GetString("MainWindow_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpreadSheets Reports Designer.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        public static string ReportSectionEditor_AddRow {
            get {
                return ResourceManager.GetString("ReportSectionEditor_AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ReportSectionEditor_Create {
            get {
                return ResourceManager.GetString("ReportSectionEditor_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detial.
        /// </summary>
        public static string ReportSectionEditor_Detail {
            get {
                return ResourceManager.GetString("ReportSectionEditor_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string ReportSectionEditor_Footer {
            get {
                return ResourceManager.GetString("ReportSectionEditor_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string ReportSectionEditor_HeaderText {
            get {
                return ResourceManager.GetString("ReportSectionEditor_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ReportSectionEditor_Properties {
            get {
                return ResourceManager.GetString("ReportSectionEditor_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sheet.
        /// </summary>
        public static string SheetCollectionEditor_AddSheet {
            get {
                return ResourceManager.GetString("SheetCollectionEditor_AddSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SheetCollectionEditor_RemoveSheet {
            get {
                return ResourceManager.GetString("SheetCollectionEditor_RemoveSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Column.
        /// </summary>
        public static string SheetEditor_AddColumn {
            get {
                return ResourceManager.GetString("SheetEditor_AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string SheetEditor_Resize {
            get {
                return ResourceManager.GetString("SheetEditor_Resize", resourceCulture);
            }
        }
    }
}
